FROM oven/bun:1

WORKDIR /app

COPY package.json package-lock.json* ./
RUN bun install

COPY . .

EXPOSE 8081 19000 19001 19002

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

CMD ["bunx", "expo", "start", "--web"]
