FROM archlinux/archlinux:base-devel

WORKDIR /app

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm curl unzip && \
    pacman -Scc --noconfirm

RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:${PATH}"

COPY package.json bun.lockb* ./
RUN bun install

COPY . .

EXPOSE 19000 19001 19002

CMD ["bun", "start"]
