FROM archlinux/archlinux:base-devel

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=1000

WORKDIR /workspace

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
    curl \
    git \
    bash \
    libffi \
    openssl \
    openssh \
    unzip \
    make \
    zlib \
    bzip2 \
    readline \
    sqlite \
    xz \
    tk \
    && pacman -Scc --noconfirm

RUN groupadd -g ${USER_GID} ${USERNAME} && \
    useradd -m -u ${USER_UID} -g ${USERNAME} ${USERNAME}

USER ${USERNAME}

# Install pyenv
RUN curl https://pyenv.run | bash

ENV PYENV_ROOT="/home/${USERNAME}/.pyenv"
ENV PATH="${PYENV_ROOT}/bin:${PATH}"

# Install Python 3.11 via pyenv
RUN eval "$(pyenv init -)" && pyenv install 3.11 && pyenv global 3.11

RUN eval "$(pyenv init -)" && pip install --no-cache-dir --user hatch
RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/home/${USERNAME}/.local/bin:/home/${USERNAME}/.bun/bin:${PYENV_ROOT}/shims:${PATH}"

EXPOSE 5173 8000 19000 19001 19002

CMD ["/bin/bash"]
