FROM python:3.11-alpine

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

RUN pip install --no-cache-dir hatch

COPY pyproject.toml ./
RUN hatch env create

COPY . .

EXPOSE 8000

CMD ["hatch", "run", "dev"]
