FROM archlinux/archlinux:base-devel

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm python python-pip && \
    pacman -Scc --noconfirm

RUN pip install --no-cache-dir hatch

COPY pyproject.toml ./
RUN hatch env create

COPY . .

EXPOSE 8000

CMD ["hatch", "run", "dev"]
